return {
  ["Bloody Pearl"] = {
    typeName = "Bloody Pearl",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 103 },
  ["Effervescent Brimstone"] = {
    typeName = "Effervescent Brimstone",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 1 },
  ["Void Umbalite"] = {
    typeName = "Void Umbalite",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 67 },
  ["Brawler's Gem"] = {
    typeName = "Brawler's Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 49 },
  ["Gem of the Earth"] = {
    typeName = "Gem of the Earth",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 31 },
  ["Gem of the Warlord"] = {
    typeName = "Gem of the Warlord",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 31 },
  ["Tyrannical Gem"] = {
    typeName = "Tyrannical Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 1 },
  ["Golem's Onyx"] = {
    typeName = "Golem's Onyx",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 85 },
  ["Solar Gem"] = {
    typeName = "Solar Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 43 },
  ["Dragonfire Spessartite"] = {
    typeName = "Dragonfire Spessartite",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 43 },
  ["Gem of the Frozen Queen"] = {
    typeName = "Gem of the Frozen Queen",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 37 },
  ["Whispering Tentaculite"] = {
    typeName = "Whispering Tentaculite",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 7 },
  ["Lunar Gem"] = {
    typeName = "Lunar Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 37 },
  ["Gem of the Combatant"] = {
    typeName = "Gem of the Combatant",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 61 },
  ["Slipstream Gem"] = {
    typeName = "Slipstream Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 7 },
  ["Celsius' Tear"] = {
    typeName = "Celsius' Tear",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 13 },
  ["Splendor Gem"] = {
    typeName = "Splendor Gem",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 19 },
  ["Charged Lodestone"] = {
    typeName = "Charged Lodestone",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 79 },
  ["Gem of the Verdant Ruin"] = {
    typeName = "Gem of the Verdant Ruin",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 25 },
  ["Breach Gem"] = {
    typeName = "Breach Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 55 },
  ["Mossy Agate"] = {
    typeName = "Mossy Agate",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 91 },
  ["Gem of the Samurai"] = {
    typeName = "Gem of the Samurai",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 19 },
  ["Luminous Opal"] = {
    typeName = "Luminous Opal",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 97 },
  ["Gem of the Twilight Forest"] = {
    typeName = "Gem of the Twilight Forest",
    chestName = "ironchest:diamond_chest_44",
    startSlot = 49 },
  ["Lightning Gem"] = {
    typeName = "Lightning Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 25 },
  ["Ballast Gem"] = {
    typeName = "Ballast Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 73 },
  ["Guardian Gem"] = {
    typeName = "Guardian Gem",
    chestName = "ironchest:diamond_chest_46",
    startSlot = 13 },
}